/* Vragen en meldkamerteksten. Verander alleen de tekst tussen aanhalingstekens. */
const VRAGEN={
 opening:{ask:'112, welke hulpdienst wilt u spreken: ambulance, brandweer of politie?',short:'Welke hulpdienst wilt u spreken?'},
 incident:{ask:'Wat is het noodgeval?',short:'Wat is er aan de hand?'},
 address:{ask:'Wat is het adres? Noem straat, huisnummer en plaats.',short:'Wat is het adres?'},
 ambOpen:{ask:'Meldkamer ambulance, wat is het noodgeval?',short:'Wat is er aan de hand?'},
 unresp:{ask:'Reageert {hij} als u {hem} aanspreekt en voorzichtig aan de schouders schudt?',short:'Reageert {hij}?'},
 breath:{ask:'Ademt {hij} normaal?',short:'Is de ademhaling normaal?'},
 confirm:{ask:'Klopt het adres?',short:'Klopt het adres?'},
 gpsConfirm:{ask:'Ik zie in deze oefening uw GPS-locatie in het Haagse Bos in Den Haag. Bent u daar?',short:'Bent u in het Haagse Bos?'},
 waterSafety:{ask:'Is de persoon al uit het water en kunt u veilig helpen?',short:'Is de persoon veilig uit het water?'},
 know:{ask:'Weet u wat u moet doen bij het reanimeren?',short:'Weet u wat u moet doen?'},
 clarify:{ask:'Waar twijfelt u over? Ik help u daarbij.',short:'Waar heeft u hulp bij nodig?'},
 assessment:{ask:'Wat ziet u precies? Reageert de persoon duidelijk en ademt die normaal?',short:'Wat ziet u nu?'},
 access:{ask:'Waar in het gebouw ligt de persoon? Welke ingang kunnen de hulpverleners gebruiken?',short:'Waar ligt de persoon precies?'}
};

const TEKST={
  locatieOpvragen:'Ik ga uw locatie opvragen, zodat ik kan zien waar u bent.',
  locatieHerkenbaar:'U bent bij {locatie}. Ik geef die locatie door aan de hulpverleners. Vertel het als dat niet klopt.',
  locatieHogeschool:'De Haagse Hogeschool, dat is {adres}. Ik stuur de hulp naar dat adres. Geef het aan als u op een andere locatie bent.',
  zin001:'Zet het volume hoog. De meldkamer luistert als het bolletje groen is.',
  zin002:'Deze browser ondersteunt geen spraakherkenning. Gebruik Safari op de iPhone of Chrome op Android.',
  zin003:'Deze app of browser ondersteunt geen spraakherkenning. Open de link in Safari (iPhone) of Chrome (Android), niet in de Claude-app.',
  zin004:'Geen toegang tot de microfoon. Open de link in Safari of Chrome en tik op Toestaan als om de microfoon wordt gevraagd.',
  zin005:'Spraakherkenning staat uit. Zet op de iPhone Siri en Dicteren aan via Instellingen, of gebruik Chrome.',
  zin006:'Spraakherkenning heeft een internetverbinding nodig.',
  zin007:'Er zijn twee ambulances met spoed naar u onderweg. De burgerhulpverlening is geactiveerd. Er kunnen burgerhulpverleners bij u aankomen, mogelijk met een AED. Ik blijf aan de lijn.',
  zin008:'. Klopt dat? Ik kan de GPS-locatie doorgeven aan de hulpverleners.',
  zin009:'Ziet u een herkenningspunt, zoals een brug, pad, bord of ingang? Blijf bij de persoon.',
  zin010:'Weet u wat u moet doen bij de reanimatie van een drenkeling?',
  zin011:'Een moment, ik verbind u door met de meldkamer ',
  zin012:'Dan klopt de locatie op mijn scherm niet. Waar bent u wel?',
  zin013:' door aan de hulpverleners. U hoeft geen straat of huisnummer te zoeken.',
  zin014:'Ga niet zelf het water in als dat onveilig is. Ik geef door dat redding uit het water nodig is. De hulpdiensten worden voor een waterredding ingezet. Blijf op een veilige plek. Vertel het zodra de persoon veilig uit het water is.',
  zin015:'Houd de luchtweg vrij en blijf de ademhaling controleren.',
  zin016:'Blijf bij de persoon en houd de luchtweg vrij. Ik blijf aan de lijn. Vertel het meteen als de toestand verandert.',
  zin017:'Prima, goed dat u al iemand voor de AED heeft gestuurd.',
  zin018:'Ik noteer uw opgegeven locatie en geef die door aan de hulpverleners.',
  zin019:'Ik heb nog het volledige adres nodig, met huisnummer en plaats.',
  zin020:'Ik hoor de sirene, de ambulance is er bijna. Laat iemand hen opvangen en de weg wijzen. Ga door tot het ambulanceteam het overneemt.',
  zin021:'Ik hoor de sirene, de ambulance is er bijna. Blijf bij de persoon en ga door tot het ambulanceteam het overneemt.',
  zin022:'De ambulance is bij u. Ga door totdat de hulpverleners het overnemen. Geef daarna kort door wat er is gebeurd en wat de AED heeft aangegeven.',
  zin023:'Duidelijk, er is nog iemand bij u. Laat die persoon zo nodig helpen of straks het drukken overnemen. Wissel ongeveer elke twee minuten, liefst tijdens de analyse van de AED.',
  zin024:'Duidelijk, u bent nu alleen bij de persoon. Blijf reanimeren en houd de telefoon op de luidspreker. Zeg het zodra uw collega terug is.',
  zin025:'Duidelijk, u bent alleen. Ik blijf aan de lijn. {door}',
  zin026:'Blijf stevig en snel drukken, ongeveer twee keer per seconde. Ik blijf aan de lijn.',
  zin027:'Gaat het nog? We doen dit stap voor stap. De hulp is onderweg.',
  zin028:'Het is bijna twee minuten. Wissel straks van wie er drukt, snel en zonder pauze.',
  zin029:'Houd vol, de hulp komt eraan. Ik blijf aan de lijn.',
  zin030:'Weer twee minuten. Wissel als dat kan, zonder pauze.',
  zin031:'(aed|a e d|a\\.e\\.d|ae d|a ee d|defibrillator|hartstarter)',
  zin032:'Fijn. Vertel de hulpverleners waar de persoon ligt, en geef kort door wanneer u hem aantrof, wanneer de reanimatie begon en wat de AED heeft aangegeven. Laat hen de zorg overnemen. Ik hang nu op.',
  zin033:'De ambulances zijn met spoed onderweg. Een exacte tijd kan ik niet geven. Ik blijf aan de lijn. {door}',
  zin034:'De ambulancezorg en burgerhulpverlening zijn gealarmeerd. Ik geef uw vraag over politie door.',
  zin035:'De ambulancezorg en burgerhulpverlening zijn gealarmeerd. Ik geef uw vraag over brandweer door.',
  zin036:'Dat is goed. Blijf zonder onderbreking borstcompressies geven. Ik blijf aan de lijn.',
  zin037:'Kantel het hoofd iets verder achterover en til de kin op. Probeer het nog één keer en ga dan direct verder met drukken.',
  zin038:'Kantel het hoofd achterover en til de kin op. Na dertig keer drukken geeft u twee rustige beademingen, tot u de borstkas ziet omhoogkomen. Ga dan direct verder met drukken.',
  zin039:'Ga daarmee door: dertig keer drukken en twee keer beademen, met zo kort mogelijke pauzes. Lukt beademen niet, dan alleen drukken.',
  zin040:'Dat geeft niet. Blijf stevig en snel drukken, ongeveer twee keer per seconde.',
  zin041:'Blijf in een stevig ritme drukken, ongeveer twee keer per seconde. Laat de borstkas na elke keer helemaal terugveren.',
  zin042:'Midden op de borstkas, handen op elkaar, armen gestrekt. Vijf tot zes centimeter diep, ongeveer twee keer per seconde.',
  zin043:'Ik begrijp dat het spannend is. De persoon reageert niet en ademt niet normaal. Blijf op de borstkas drukken, ik begeleid u.',
  zin044:'Nee, ga door tot de AED zegt dat u moet stoppen of tot de ambulance het overneemt.',
  zin045:'Draai het hoofd even opzij en maak de mond schoon. Is {hij} duidelijk bij bewustzijn en ademt {hij} normaal? Zo niet, ga direct weer verder.',
  zin046:'Goed. Laat iemand bij de ingang staan om de ambulance de weg te wijzen.',
  zin047:'U blijft bij de persoon. Ik geef de ingang door aan de ambulance.',
  zin048:'Ga door met reanimeren, dat is nu het belangrijkste. De ambulance kijkt daar straks naar.',
  zin049:'De AED kan gewoon gebruikt worden. Plak de elektrode niet op het zichtbare apparaat, maar er iets naast, en volg de AED.',
  zin050:'Ga gewoon door met reanimeren. Ik geef het door aan de ambulance.',
  zin051:'Droog de plekken voor de elektroden snel af, zodat ze goed contact maken. Plak ze en volg de AED.',
  zin052:'Scheer of trek het haar weg waar de elektroden komen, als er een scheermesje bij de AED zit. Anders stevig aandrukken.',
  zin053:'Zorg dat de elektroden niet op metaal komen. Schuif het opzij en plak op de blote huid.',
  zin054:'Dit oefenscenario is voor een volwassene. Voor kinderen en baby\'s gelden andere instructies; die oefent u apart.',
  zin055:'Goed. Wissel snel en ga meteen door, zonder pauze.',
  zin056:'Is er iemand bij u gekomen? Laat die het drukken dan overnemen, zonder pauze.',
  zin057:'Laat de ander het drukken overnemen, snel en zonder pauze.',
  zin058:'Ik hoor dat het zwaar is. Blijf doen wat u kunt. Zodra iemand bij u komt, laat die het drukken overnemen. Ik blijf aan de lijn.',
  zin059:'De ambulances zijn onderweg. Ga door tot de hulpverleners het van u overnemen.',
  zin060:'Vijf tot zes centimeter diep, ongeveer twee keer per seconde. Laat de borstkas steeds helemaal terugkomen.',
  zin061:'Dat kan gebeuren. Ga gewoon door, dat is nu het belangrijkste.',
  zin062:'Ik blijf aan de lijn. We doen dit stap voor stap.',
  zin063:'Blijf bij {hem} en controleer de ademhaling en reactie voortdurend. Houd de luchtweg vrij. Laat de AED aan en de elektroden zitten. Vertel het meteen als het slechter gaat. Stopt het normale ademen, begin dan direct weer met reanimeren.',
  zin064:'Wat doet {hij} precies? Opent {hij} de ogen, reageert {hij} duidelijk en ademt {hij} normaal? Bij twijfel gaat u door met reanimeren.',
  zin065:'Zorg dat niemand de persoon aanraakt. Volg de AED voor de schok en ga daarna direct verder met reanimeren.',
  zin066:'Raak de persoon nu niet aan, en zorg dat niemand anders dat doet.',
  zin067:'Volg de AED en ga direct verder met reanimeren.',
  zin068:'Goed. Ga direct weer verder met reanimeren, zoals de AED zegt.',
  zin069:'Ja. Ga door met drukken, en beademen als u dat kunt. Ik blijf aan de lijn.',
  zin070:'Goed. Ga zo veel mogelijk door met drukken terwijl de elektroden worden geplakt. Daarna volgt u de gesproken aanwijzingen.',
  zin071:'Goed. Volg de gesproken aanwijzingen van de AED. Ik blijf aan de lijn.',
  zin072:'Haal die AED en kom meteen terug naar de persoon. Zet hem aan en volg de gesproken aanwijzingen.',
  zin073:'Ik hoor u. Blijf nu drukken. Zodra iemand terugkomt, vertel me dat; dan help ik u met de AED.',
  zin074:'Er is op dit moment geen AED in de buurt beschikbaar. De ambulance neemt er een mee. {door}',
  zin075:'Ik heb burgerhulpverleners met een AED gealarmeerd. Is er in het gebouw een AED, laat die dan halen als er iemand is die dat kan. {door}',
  zin076:'Duidelijk, de AED wordt gehaald en u bent nu alleen bij de persoon. Blijf reanimeren. Zeg het zodra uw collega terug is.',
  zin077:'Goed, de AED is onderweg en er is nog iemand bij u. Laat die zo nodig helpen of straks het drukken overnemen.',
  zin078:'Goed dat de AED wordt gehaald. Is er nu nog iemand anders bij u?',
  zin079:'.{0,15}((is|zijn) (er|hier|binnen|aangekomen|gearriveerd|gebracht|terug)|ligt (hier|er)|staat hier|hangt hier|is gekomen)|terug met (de |een )?',
  zin080:'Laat de AED aanzetten en de elektroden aanbrengen, terwijl u zo veel mogelijk doorgaat met drukken. Volg de gesproken aanwijzingen.',
  zin081:'Zet de AED aan. Maak de borstkas vrij en plak de elektroden volgens de afbeeldingen. Volg de gesproken instructies.',
  zin082:'Ga door met reanimeren. Geef aan als u hulp nodig heeft.',
  zin083:'Ik help u. Plaats de hiel van uw hand midden op de borst en uw andere hand daar bovenop. Houd uw armen gestrekt. Druk vijf tot zes centimeter diep, honderd tot honderdtwintig keer per minuut. Laat de borst na elke druk helemaal terugveren. Begin nu met dertig borstcompressies. Geef daarna twee beademingen: kantel het hoofd achterover, til de kin op en knijp de neus dicht. Sluit uw mond om de mond van de persoon en blaas rustig één seconde, totdat de borst omhoogkomt. Laat de borst dalen en geef de tweede beademing. Ga direct verder met dertig borstcompressies. Blijf dertig compressies en twee beademingen afwisselen. Houd de onderbreking zo kort mogelijk, bij voorkeur maximaal vijf seconden. Lukt beademen niet of wilt u niet beademen, blijf dan zonder onderbreking borstcompressies geven. Volg de AED zodra die er is. Ik blijf aan de lijn.',
  zin084:'Ik help u. Geef eerst vijf beademingen: kantel het hoofd achterover, til de kin op en knijp de neus dicht. Sluit uw mond om de mond van de persoon. Blaas telkens rustig één seconde zodat de borst omhoogkomt en laat die weer dalen. Geef daarna dertig borstcompressies midden op de borst, vijf tot zes centimeter diep en honderd tot honderdtwintig keer per minuut. Laat de borst terugveren. Wissel vervolgens dertig compressies en twee beademingen af. Als beademen niet lukt, geef borstcompressies en zeg het, dan help ik u verder. Volg de AED zodra die er is.',
  zin085:'Zet uw telefoon op de luidspreker en leg hem naast u neer.',
  zin086:'Er is nog iemand bij u: wissel ongeveer elke twee minuten van wie er drukt, liefst tijdens de analyse van de AED.',
  zin087:'U bent nu alleen bij de persoon. Zeg het zodra uw collega terug is.',
  zin088:'Is er een AED ter plaatse, of wordt die gehaald?',
  zin089:'Waar in het gebouw ligt de persoon en welke ingang kunnen de hulpverleners gebruiken?',
  zin090:'Kan een andere helper de hulpverleners bij een pad of ingang opvangen?',
  zin091:'Kan iemand de ambulance bij de ingang opvangen?',
  zin092:'Ga door totdat de hulpverleners het overnemen.',
  zin093:'Geef kort door wat er is gebeurd, wanneer u begon en wat de AED heeft aangegeven. Bedankt voor uw inzet.',
  zin094:'Beademingen zijn bij verdrinking extra belangrijk. Wat lukt er niet? Als beademen niet lukt, blijf borstcompressies geven terwijl ik u help.',
  zin095:'Kantel het hoofd achterover en til de kin op. Knijp de neus dicht, sluit uw mond om de mond en blaas rustig totdat de borst omhoogkomt. Lukt dat niet na twee pogingen, ga direct verder met borstcompressies.',
  zin096:'Twee ambulances zijn met spoed onderweg en burgerhulpverlening is geactiveerd. Een exacte aankomsttijd kan ik niet geven. Ik blijf aan de lijn.',
  zin097:'Prima, goed dat u dat heeft geregeld. Ga ondertussen door met reanimeren. Laat weten zodra de AED er is.',
  zin098:'Is het mogelijk om iemand voor een AED te sturen?',
  zin099:'Goed. Laat die persoon de AED halen en terugbrengen. Ga ondertussen door met reanimeren.',
  zin100:'Is er een AED die u binnen één minuut beschikbaar kunt hebben?',
  zin101:'Kan die persoon bij de receptie of BHV navragen waar een AED is?',
  zin102:'Bent u alleen, of is er iemand die kan helpen?',
  zin103:'Haal de AED en kom meteen terug. Zet hem aan en volg de aanwijzingen.',
  zin104:'Ga door met reanimeren. De ambulances zijn onderweg en burgerhulpverlening is geactiveerd.',
  zin105:'Is de AED al bij de persoon, of moet die nog gehaald worden?',
  zin106:'Dank u, ik geef deze locatie door aan de hulpverleners.',
  zin107:'Goed geregeld. Laat die persoon de hulpverleners de weg wijzen.',
  zin108:'Ik heb burgerhulpverleners met een AED gealarmeerd. Laat iemand kijken of er in het gebouw een AED hangt en die halen.',
  zin109:'Blijf bij de persoon en ga door met reanimeren. Ik heb burgerhulpverleners met een AED gealarmeerd.',
  zin110:'Dat weet ik niet precies. De hulp is onderweg en ik blijf aan de lijn. {door}',
  zin111:'De 112-centralist vraagt eerst: politie, brandweer of ambulance? Zeg meteen "ambulance".',
  zin112:'Tel hardop tot 10 terwijl je naar de borst kijkt. De meldkamer wacht daarop.',
  zin113:'Adres, geen reactie en geen normale ademhaling: alles in één keer.',
  zin114:'De app kon het adres niet goed verstaan. Controleer of je het juiste adres noemde: ',
  zin115:'Je hoeft niet te wachten op de meldkamer: begin zodra je weet dat hij niet normaal ademt.',
  zin116:'De centralist vraagt alleen ontbrekende informatie. Aanvullende vragen houden de inzet van hulp niet tegen.',
  zin117:'Happen of snurken is geen normale ademhaling.',
  zin118:'Hij reageerde niet op aanspreken en schudden.',
  zin119:'Zet de luidspreker aan zodra je belt, dan heb je je handen vrij voor de reanimatie.',
  zin120:'De meldkamer las het adres bewust verkeerd voor. Luister goed en verbeter het meteen.',
  zin121:'Vanaf het bellen tot twee ambulances en burgerhulpverlening zijn gealarmeerd.',
  zin122:'Zeg het tegen de meldkamer als de AED er is. De meldkamer wordt dan stil, zodat je de AED goed hoort.',
  zin123:'Bespreek met de instructeur de feedback van de oefenpop over diepte en tempo.',
  zin124:'één één twee. Heeft u politie, brandweer of ambulance nodig?',
  zin125:'Meldkamer ambulance. Waar bent u precies? Is er een AED ter plaatse?',
  zin126:'. Mis je een stem die je net hebt gedownload? Sluit Safari dan helemaal af en open de app opnieuw.',
  zin127:'Geluid: hoor je een toon en een stem? Zo niet, zet het volume hoger en de stille modus uit. Microfoon: ',
  zin128:'Je hoort nu een toon en een stem. Zeg daarna iets…',
  zin129:'Er is niets gehoord. Probeer het nog eens en praat wat harder.'
};
